blank_issues_enabled: true
contact_links:
  - name: 📋 飞书反馈表
    url: https://mcn4ryw5oh8e.feishu.cn/wiki/CwcuwZxhiiRMbZkgqCtcUhAOn9f?table=tbleXMW2b9LVzvk5&view=vew7uMRjLU
    about: 通过飞书提交反馈
  - name: 📧 邮件联系
    url: mailto:du.upup@gmail.com
    about: 通过邮件联系我们
